.circleci/config.yml, scripts/npm-audit-fix.sh
This adds a CircleCI config that is able to run the usual linting and testing over Node 11, 10, 9, and 8. (The Realms shim fails on Node 7 and 6).
It also adds a cron job that automatically submits a PR if the nightly run finds anything changed after `npm audit fix` is run.
=> Add CircleCI config

package.json
This PR enables `npm test` as an alias for `npm run shim:test`
=> Add npm test as an alias for `npm run shim:test`

package-lock.json, package.json
This PR runs `npm audit fix --force` which installs nyc 14.0.0 which resolves this Prototype Pollution issue with handlebars.
=> result of running ` npm audit fix --force`

src/sourceParser.js, test/realm/test-import-expression.js
This PR simplifies the `importParser` regexp and fixes line number detection.
=> Simplify importParser regexp and fix line number detection

src/evaluators.js, test/realm/test-confinement.js
https://github.com/Agoric/realms-shim/pull/17 raises the issue of the `this` binding of `Function` constructor.
We had missing test cases, whose absence would be informative on that PR. This PR adds those test cases.
=> add testcase for other Function this bindings

src/evaluators.js, src/realm.js, src/realmFacade.js, src/sourceParser.js, test/module/evaluators.js, test/module/realmFacade.js
Provide a more generalized rewrite/endow mechanism to allow for pluggable source transformations.
This moves the work of infix-bang and import/export rewrites to the realm-creating host instead of builtin functionality.
=> generic source transforms

examples/simple.js
the example was broken (not sure for how long) because it was using direct eval form on the sanity checks.
for now, I just removed the sanity checks since we now have proper tests. another alternative is to preserve the sanity checks but use indirect eval form instead of direct eval for those checks.
=> fixing examples/simple.js due to new direct eval restrictions

src/evaluators.js, src/realm.js, src/scopeHandler.js, test/module/evaluators.js, test/module/utilities.js
This option designates the object that is used as a backing store
for assignments to names that aren't bound elsewhere.  This allows
the creation of realms and compartments that can share mutable global state
among separate evaluations.
=> options.sloppyGlobals: object to receive REPL variable assigments

test/module/evaluators.js
This line escaped me during the sloppyGlobals merge.
It accidentally disabled most of the test suite.
=> test/module/evaluators.js: remove test.only

src/evaluators.js, test/module/evaluators.js
This reordering of the transforms phasing makes it possible for a
rewriter to affect the actual endowments.
I found I need this in order to implement the `import()` expression transform correctly: it is a source-dependent endowment that can't easily be defined before the rewrite transform takes place without terrible hacks.
=> evaluators.js: allow transform.rewrite() to change endowments

src/evaluators.js
Fix https://github.com/Agoric/realms-shim/issues/48
Breakout via RangeError: Maximum call stack size exceeded
Remove handler singleton.
=> Fix issue #48 Breakout via RangeError

package-lock.json, package.json, rollup.config.js
This PR addresses #29 by tweaking the build script to generate unminified CJS output. The rest of the package is in great shape for publishing so nothing needed there. I tested what the published package would generate with `npm pack`.
At the moment before publishing you should run `npm run shim:build` and then `npm publish`. For the publishing account used I assume it would be an Agoric user _(number of accounts with publish access should be limited as they each are a security point)_. 
You should have 2factor authentication enabled for login and writes. See https://docs.npmjs.com/about-two-factor-authentication#authorization-and-writes. Besides the command-line way to enable 2factor authentication there is also a web UI way through the [npm site](https://www.npmjs.com/) once logged in. …
=> Prepare package for publishing.

package-lock.json, package.json, src/repair/functions.js, src/unsafeRec.js
rollup is apparently allergic to the `(1, eval)(...)` trick to
avoid direct eval.  Binding eval to a different name is the only
way it supports usage without mangling.
This doesn't cause a failure of our tests, but when something
(like SES) imports `realms-shim`, the `repairFunctions` fails,
as rollup has rewritten `(1, eval)(...)` to something like
`(1, _f4f.e)(...)`.
=> repairFunctions: use globalEval binding to placate rollup

src/scopeHandler.js, test/module/scopeHandler.js
related to https://github.com/Agoric/realms-shim/pull/17#issuecomment-510201945
=> fix: getPrototypeOf trap get called in safari

src/callAndWrapError.js, src/childRealm.js, src/evaluators.js, src/realm.js, src/safeEval.js, src/safeFunction.js, src/scopeHandler.js, src/unsafeRec.js, test/module/childRealm.js, test/module/evaluators.js, test/module/scopeHandler.js, test/realm/leak-unsafe-eval.js
- Remove module name suffix *Facade
- Use realmRec.unsafeEval directly
- Reduce impact of esm in tests by capturing eval
- Remove console output from OOM tests.
=> Refactor evaluation stringified functions

src/realm.js, src/stdlib.js, src/unsafeRec.js, test/realm/test-shims.js
This feature fixes a TODO that said the fast freezing of globals
that are generally "stable" is for performance, but isn't totally
correct.
The test case shows how to use it.
I've run into problems trying to provide a wrapper for all globals
from within a shim.  Notably, it was impossible to replace Array,
Object, and other functions in the global namespace because they
are frozen.
=> Allow shims to mutate all globals with options.configurableGlobals

src/sourceParser.js, test/module/evaluators.js, test/realm/test-import-expression.js
This change allows import expressions to be used within JSDoc blocks.
It takes advantage of the fact that `@param {import(...)}` is not valid Javascript syntax, not even after decorators are landed, so it cannot be an evaluable import expression.
https://github.com/Agoric/SES-shim/issues/261
=> Don't explode on JSDoc import expressions

src/sourceParser.js, test/realm/test-import-expression.js
Refs #124
This adds more support for JSDoc imports, namely:
```js
/**
* @param {typeof import('./foo.js').Obj}
* @param {keyof typeof import('./foo.js').Obj}
*/
```
=> Also allow `typeof` JSDoc imports.

src/repair/accessors.js, test/module/accessors.js
This makes the repaired accessors throw a `TypeError` when invoked with `new`.
=> fix(repair‑accessors): disallow `new` invocation

README.md, SECURITY.md
As discussed, this updates the README and SECURITY.md to reflect the deprecation of this package.
=> chore: mark package as deprecated and insecure
